import Navbar from "@/components/Nabar"
import { useAppSelector } from "@/redux/hooks"

export const metadata = {
    title: 'Reciever Portal',
    description: 'Generated by Next.js',
}

export default function RecieverLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}
